apiVersion: apps/v1
kind: Deployment
metadata:
  name: foxids-deployment
  labels:
    app: foxids
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foxids
  template:
    metadata:
      labels:
        app: foxids
    spec:
      containers:
        - name: foxids
          image: localhost:32000/foxids
          ports:
            - containerPort: 5000
        - name: foxids-control
          image: localhost:32000/foxids-control
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: foxids
spec:
  selector:
    app: foxids
  ports:
    - protocol: TCP
      port: 44331
      targetPort: 44331
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foxids
            port:
              number: 5001
