apiVersion: cert-manager.io/v1
kind: Issuer
metadata: 
  name: letsencrypt-staging 
spec:
  acme:   
    server: https://acme-staging-v02.api.letsencrypt.org/directory 
    email: support@my-domain.com # change to your email
    privateKeySecretRef:     
     name: letsencrypt-staging 
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata: 
  name: letsencrypt-production 
spec:
  acme:   
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: support@my-domain.com # change to your email
    privateKeySecretRef:     
      name: letsencrypt-production 
    solvers:
      - http01:
          ingress:
            class: nginx