apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foxids-ingress-http
  annotations:
   #Rate Limiting
   #nginx.ingress.kubernetes.io/limit-connections: "20"
   #nginx.ingress.kubernetes.io/limit-rpm: "300"
   #nginx.ingress.kubernetes.io/limit-rps: "10"
   #nginx.ingress.kubernetes.io/limit-whitelist: "xxx.xxx.xxx.xxx" # your IP Address
   #Buffer
   nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
   nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
   #Certificate
   cert-manager.io/issuer: "letsencrypt-production" #production    
   #cert-manager.io/issuer: "letsencrypt-staging" #staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - id.itfoxtec.com   # change to your domain -  id.my-domain.com
      - control.itfoxtec.com  # change to your domain -  control.my-domain.com
      secretName: letsencrypt-production-tls #production  
      #secretName: letsencrypt-staging-tls #staging
  rules:
  - host: id.itfoxtec.com   # change to your domain -  id.my-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foxids
            port:
              number: 8800
  - host: control.itfoxtec.com   # change to your domain -  control.my-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foxids-control
            port:
              number: 8800