apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foxids-ingress-http
  annotations:
   cert-manager.io/cluster-issuer: "letsencrypt-production" #production    
   #cert-manager.io/cluster-issuer: "letsencrypt-staging" #staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - id.itfoxtec.com   # change to your domain -  id.my-domain.com
      - control.itfoxtec.com  # change to your domain -  control.my-domain.com
      secretName: letsencrypt-production-tls #production  
      #secretName: letsencrypt-staging-tls #staging
  rules:
  - host: id.itfoxtec.com   # change to your domain -  id.my-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foxids
            port:
              number: 8800
  - host: control.itfoxtec.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foxids-control
            port:
              number: 8800