apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 #production 
  name: letsencrypt-production
 #staging
 # name: letsencrypt-staging
spec:
  acme:
   #production
    server: https://acme-v02.api.letsencrypt.org/directory
   #staging
   # server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: support@my-domain.com # change to your email
    privateKeySecretRef:
     #production 
      name: letsencrypt-production
     #staging
     # name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx