apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    # local directory c:\data\foxids-data\mongo on Docker Desktop host machine
    path: "/run/desktop/mnt/host/c/data/foxids-data/mongo"
    type: ""