apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foxids-ingress-http
  annotations:
   #production 
    cert-manager.io/cluster-issuer: letsencrypt-production
   #staging
   # cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  rules:
  - host: id.itfoxtec.com   # change to your domain -  id.my-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foxids
            port:
              number: 8800
  - host: control.itfoxtec.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foxids-control
            port:
              number: 8801
  tls:
    - hosts:
      - id.itfoxtec.com   # change to your domain -  id.my-domain.com
      - control.itfoxtec.com  # change to your domain -  control.my-domain.com
     #production 
      secretName: letsencrypt-production
     #staging 
     # secretName: letsencrypt-staging