name: ci_main_docker

on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: get-version
        with:
          proj-path: src/FoxIDs/FoxIDs.csproj
      -
        name: Docker meta
        id: meta-f
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/foxids
          tags: |            
            type=raw,value=${{ steps.get-version.outputs.version }}
            type=raw,value=latest,enable=true
      -
        name: Docker meta
        id: meta-fc
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/foxids-control
          tags: |     
            type=raw,value=${{ steps.get-version.outputs.version }}
            type=raw,value=latest,enable=true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push FoxIDs
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/FoxIDs/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-f.outputs.tags }}
          labels: ${{ steps.meta-f.outputs.labels }}
      -
        name: Build and push FoxIDs.Control
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/FoxIDs.Control/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-fc.outputs.tags }}
          labels: ${{ steps.meta-fc.outputs.labels }}

      - name: Docker Hub Description FoxIDs
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/foxids
          readme-filepath: ./Docker/README-FoxIDs-image.md
          short-description: "FoxIDs is a Identity Services (IDS) supporting: login, OAuth 2.0, OpenID Connect 1.0 and SAML 2.0."

      - name: Docker Hub Description FoxIDs.Control
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/foxids-control
          readme-filepath: ./Docker/README-FoxIDs-Control-image.md
          short-description: "FoxIDs is a Identity Services (IDS). FoxIDs Control is the admin site."