name: ci_release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
#    runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: General build for test
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: get-version
        with:
          proj-path: src/FoxIDs/FoxIDs.csproj





      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
