name: ci_test_docker

on:
  push:
    branches:
      - "test"
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: General build for test
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: get-version
        with:
          proj-path: src/FoxIDs/FoxIDs.csproj

      - name: Docker meta
        id: meta-f
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ secrets.DOCKERHUB_ORG }}/foxids
          tags: |            
            type=raw,value=latest-test,enable=true

      - name: Docker meta
        id: meta-fc
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ secrets.DOCKERHUB_ORG }}/foxids-control
          tags: |     
            type=raw,value=latest-test,enable=true

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0

      - name: Build and push FoxIDs
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: ./src/FoxIDs/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ${{ steps.meta-f.outputs.tags }}
          labels: ${{ steps.meta-f.outputs.labels }}

      - name: Build and push FoxIDs.Control
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          file: ./src/FoxIDs.Control/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ${{ steps.meta-fc.outputs.tags }}
          labels: ${{ steps.meta-fc.outputs.labels }}

      - name: Docker Hub Description FoxIDs
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_ORG }}/foxids
          readme-filepath: ./Docker/README-FoxIDs-image.md
          short-description: "FoxIDs is an identity service (IDS) that supports login, OAuth 2.0, OpenID Connect 1.0 and SAML 2.0."

      - name: Docker Hub Description FoxIDs.Control
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_ORG }}/foxids-control
          readme-filepath: ./Docker/README-FoxIDs-Control-image.md
          short-description: "FoxIDs Control is the admin site for the Identity Service FoxIDs."