name: ci_master_docker

on:
  push:
    branches:
      - "dev_ci_docker"
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Echo version
        run: echo Version is ${{ vars.VERSION }}.${{ github.run_number }}
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push FoxIDs
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/FoxIDs/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/foxids:latest
      -
        name: Build and push FoxIDs.Control
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/FoxIDs.Control/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/foxids-control:latest
