name: ci_master_docker

on:
  push:
    branches:
      - "dev_ci_docker"
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta-f
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/foxids
          tags: |            
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
      -
        name: Docker meta
        id: meta-fc
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/foxids-control
          tags: |            
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push FoxIDs
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/FoxIDs/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-f.outputs.tags }}
          labels: ${{ steps.meta-f.outputs.labels }}
      -
        name: Build and push FoxIDs.Control
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/FoxIDs.Control/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-fc.outputs.tags }}
          labels: ${{ steps.meta-fc.outputs.labels }}
